/**
 * Generates the JavaScript `script_content` body that Proxyman runs when a
 * matching request flows through. Translates our structured spec
 * ({ matcher, jsonPatch | staticResponse }) into Proxyman's `onResponse`
 * convention.
 *
 * Two output modes:
 *   - `staticResponse`: replace status, body, and headers verbatim. The
 *     generated script doesn't touch the upstream body — Proxyman still
 *     forwards the request (we don't use `is_mock_response: true` here so the
 *     real backend still observes the call, useful for analytics audit).
 *   - `responseTransform.jsonPatch`: parse the upstream JSON, apply the patch,
 *     re-serialize. We inline a tiny RFC 6902 applier in the script so it has
 *     no external deps in Proxyman's JS runtime.
 *
 * Matcher fields beyond what Proxyman natively filters on (URL pattern, method,
 * graphqlQueryName) become guard clauses inside the script — early-return the
 * unmodified response if the request doesn't actually match. This keeps the
 * abstraction clean even when Proxyman's matching surface is narrower than ours.
 */

export interface MatcherFields {
    pathContains?: string;
    urlPathEquals?: string;
    requestBodyContains?: string;
    method?: string;
}

export interface JsonPatchOp {
    op: 'replace' | 'add' | 'remove';
    path: string;
    value?: unknown;
}

export interface StaticResponseShape {
    status?: number;
    jsonBody?: unknown;
    body?: string;
    headers?: Record<string, string>;
}

export interface ResponseTransformShape {
    jsonPatch: readonly JsonPatchOp[];
}

export interface BuildScriptInput {
    matcher: MatcherFields;
    staticResponse?: StaticResponseShape;
    responseTransform?: ResponseTransformShape;
}

/**
 * Translate our matcher into Proxyman's URL pattern. We always emit a wildcard
 * so a path-bearing request still matches when the user only gave us a host or
 * a substring — the spike showed Proxyman silently no-ops the rule otherwise.
 */
export function buildProxymanUrlPattern(matcher: MatcherFields): string {
    if (matcher.urlPathEquals) {
        // Anchor with a wildcard host segment so any host reaches this path.
        return `*${matcher.urlPathEquals}`;
    }
    if (matcher.pathContains) {
        // Pre-wrap with wildcards so the substring matches anywhere in the URL.
        return `*${matcher.pathContains}*`;
    }
    // No URL constraint → match-everything fallback. The script's body-level
    // guard will filter to the real target.
    return '*';
}

export function buildScriptContent(input: BuildScriptInput): string {
    const guards = buildGuardClauses(input.matcher);
    const action = input.staticResponse
        ? buildStaticResponseAction(input.staticResponse)
        : buildJsonPatchAction(input.responseTransform!.jsonPatch);

    return [
        '// Generated by mobile-automator-mcp — do not edit by hand.',
        'async function onResponse(context, url, request, response) {',
        ...guards,
        ...action,
        '  return response;',
        '}',
    ].join('\n');
}

function buildGuardClauses(m: MatcherFields): string[] {
    const lines: string[] = [];
    // URL-level guards Proxyman might already enforce, but we double-check
    // because URL pattern translation is best-effort.
    if (m.pathContains) {
        lines.push(`  if (!url || url.indexOf(${js(m.pathContains)}) === -1) return response;`);
    }
    if (m.urlPathEquals) {
        // Strip query string before comparing.
        lines.push(`  const _path = (url || '').split('?')[0].replace(/^https?:\\/\\/[^/]+/, '');`);
        lines.push(`  if (_path !== ${js(m.urlPathEquals)}) return response;`);
    }
    if (m.method && m.method.toUpperCase() !== 'ANY') {
        lines.push(`  if (!request || (request.method || '').toUpperCase() !== ${js(m.method.toUpperCase())}) return response;`);
    }
    if (m.requestBodyContains) {
        // Proxyman exposes request.body as either a parsed object or a string;
        // serialize defensively so substring matching works either way.
        lines.push(`  const _reqBodyStr = typeof request.body === 'string'`);
        lines.push(`    ? request.body`);
        lines.push(`    : (request.body ? JSON.stringify(request.body) : '');`);
        lines.push(`  if (_reqBodyStr.indexOf(${js(m.requestBodyContains)}) === -1) return response;`);
    }
    return lines;
}

function buildStaticResponseAction(r: StaticResponseShape): string[] {
    const lines: string[] = [];
    if (r.status !== undefined) {
        lines.push(`  response.statusCode = ${r.status};`);
    }
    if (r.jsonBody !== undefined) {
        lines.push(`  response.body = ${js(r.jsonBody)};`);
        lines.push(`  response.headers = response.headers || {};`);
        lines.push(`  if (!response.headers['Content-Type'] && !response.headers['content-type']) {`);
        lines.push(`    response.headers['Content-Type'] = 'application/json';`);
        lines.push(`  }`);
    } else if (r.body !== undefined) {
        lines.push(`  response.body = ${js(r.body)};`);
    }
    if (r.headers && Object.keys(r.headers).length > 0) {
        lines.push(`  response.headers = response.headers || {};`);
        for (const [k, v] of Object.entries(r.headers)) {
            lines.push(`  response.headers[${js(k)}] = ${js(v)};`);
        }
    }
    return lines;
}

function buildJsonPatchAction(ops: readonly JsonPatchOp[]): string[] {
    return [
        `  if (response.body && typeof response.body === 'object') {`,
        `    const _ops = ${js(ops)};`,
        `    ${JSON_PATCH_INLINE}`,
        `    try { _applyPatch(response.body, _ops); }`,
        `    catch (e) { context.log('jsonPatch failed: ' + e.message); }`,
        `  }`,
    ];
}

/**
 * Tiny inlined RFC 6902 applier (replace/add/remove) that runs inside
 * Proxyman's JS runtime. Mirrors src/wiremock/json-patch.ts but as a single
 * self-contained string so we can drop it into a script body. Mutates in place.
 */
const JSON_PATCH_INLINE = `function _applyPatch(doc, ops) {
  function tokens(p) {
    if (p === '') return [];
    if (p[0] !== '/') throw new Error('pointer must be empty or start with /: ' + p);
    return p.slice(1).split('/').map(function (t) { return t.replace(/~1/g, '/').replace(/~0/g, '~'); });
  }
  function navigate(node, ts) {
    for (var i = 0; i < ts.length; i++) {
      var t = ts[i];
      if (Array.isArray(node)) { node = node[Number(t)]; }
      else if (node && typeof node === 'object') { node = node[t]; }
      else { throw new Error('cannot navigate into primitive'); }
    }
    return node;
  }
  for (var i = 0; i < ops.length; i++) {
    var op = ops[i];
    var ts = tokens(op.path);
    if (ts.length === 0) {
      if (op.op === 'remove') throw new Error('cannot remove root');
      throw new Error('root replacement not supported in inlined patcher');
    }
    var parent = navigate(doc, ts.slice(0, -1));
    var last = ts[ts.length - 1];
    if (Array.isArray(parent)) {
      if (last === '-') {
        if (op.op !== 'add') throw new Error('"-" requires add');
        parent.push(op.value);
      } else {
        var idx = Number(last);
        if (op.op === 'replace') parent[idx] = op.value;
        else if (op.op === 'add') parent.splice(idx, 0, op.value);
        else if (op.op === 'remove') parent.splice(idx, 1);
      }
    } else if (parent && typeof parent === 'object') {
      if (op.op === 'replace') {
        if (!(last in parent)) throw new Error('cannot replace missing key ' + last);
        parent[last] = op.value;
      } else if (op.op === 'add') {
        parent[last] = op.value;
      } else if (op.op === 'remove') {
        if (!(last in parent)) throw new Error('cannot remove missing key ' + last);
        delete parent[last];
      }
    } else {
      throw new Error('parent is not an object or array');
    }
  }
}`;

/** JSON-encode a value safely as a JS literal. Strings get quoted, objects round-trip via JSON.stringify. */
function js(value: unknown): string {
    return JSON.stringify(value);
}

/** Tag a rule with the session ID so we can bulk-clean on stop_and_compile. */
export const RULE_NAME_PREFIX = 'mca';

export function buildRuleName(sessionId: string, mockId: string): string {
    return `${RULE_NAME_PREFIX}:${sessionId}:${mockId}`;
}

/** Match `mca:<sessionId>:*` rule names — used by cleanup to find session-owned rules. */
export function isOurRuleForSession(name: string, sessionId: string): boolean {
    return name.startsWith(`${RULE_NAME_PREFIX}:${sessionId}:`);
}

/** Match any `mca:*` rule name — used by global cleanup or diagnostics. */
export function isOurRule(name: string): boolean {
    return name.startsWith(`${RULE_NAME_PREFIX}:`);
}
